name: Luxury Presence Pokemon Quest
on: [push]
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Cypress.io
        uses: cypress-io/github-action@v2.9.7

        with:
          start: npm start
          browser: chrome
          headless: true
          record: true
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: 858504f0-f2d0-4f97-9991-352e25e9bc98
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
